name: PR checks

on: ['push', 'pull_request']

permissions:
  contents: read

jobs:
  lint_checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./python
        run: |
          pip install -e .[all]

      - name: Run black
        working-directory: ./python
        run: black --check ax_lang tests

      - name: Run isort
        working-directory: ./python
        run: isort --check-only ax_lang tests

      - name: Run flake8
        working-directory: ./python
        run: flake8 ax_lang tests

      - name: Run mypy
        working-directory: ./python
        run: mypy ax_lang


  run_tests:
    needs: lint_checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      working-directory: ./python
      run: |
        pip install -e .[all]

    - name: Run tests
      working-directory: ./python
      run: pytest -s -v tests/test.py
