name: Release

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v0.1.0
      - v*

jobs:
  lint_checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      working-directory: ./python
      run: |
        pip install -e .[dev]

    - name: Run black
      working-directory: ./python
      run: black --check ax_lang tests

    - name: Run isort
      working-directory: ./python
      run: isort --check-only ax_lang tests

    - name: Run flake8
      working-directory: ./python
      run: flake8 ax_lang tests

    - name: Run mypy
      working-directory: ./python
      run: mypy ax_lang

    - name: Run tests
      working-directory: ./python
      run: pytest -s -v tests/test.py

  pypi_release:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for trusted publishing

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install build dependencies
      working-directory: ./python
      run: |
        pip install build twine

    - name: Build package
      working-directory: ./python
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: python/dist/
